title: <p align="center"> Nicholas Markam </p>

logo: "Base/images/ProfilePicture.jpg?raw=true"

description: >
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/nicholasmarkram/">View My LinkedIn Profile</a> |
  <a href="https:///github.com/markramn">GitHub</a>
  </p>
  
  <p align="justify">
  My personal github portfolio shows some of the projects I have completed as my time as a data scientist. 
  Projects on here range from simple forecasting, classification exercises through to computer vision and 
  hopefully everything inbetween.
  <br><br>
  I don't only detail machine learning projects here but some interesting topics I have discovered along the way
  such as data streaming, cloud and serverless computing among others.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
